@startuml
User --> (Create account)
Cashier --> (Deposit to account)
User --> (Check balance)
User --> (Transfer money)
(Transfer money) ..> (Create transfer): includes
(Transfer money) ..> (Edit transfer): includes
(Transfer money) ..> (Commit transfer): includes
System --> (Complete transfer)
(Complete transfer) <|.. (Return transfer)
@enduml